version: '3.8'

services:

  api:
    container_name: file-browser-service
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 5004:5000
    environment:
      - FLASK_APP=src/__init__.py
      - FLASK_ENV=development
      - UPLOAD_PATH=${UPLOAD_PATH}
      - UPLOAD_PATH_TEST=${UPLOAD_PATH_TEST}
    env_file:
      - .env
