name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Dockerhub login
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag file-browser-service:$(date +%s)
    - name: Build the stack
      run: docker-compose up -d
    - name: List the container
      run: docker ps -a
    - name: Run the tests
      run: docker run file-browser-service python -m pytest "src/tests"
    - name: Smoke Test
      run: docker run --network container:file-browser-service appropriate/curl -s --retry 10 --retry-connrefused http://localhost:5000/api/
