# This workflow is triggered on pushes to the repository.
# It builds and pushes a Docker image to GitHub Packages when a release is created.
# and runs the tests.
name: Docker Compose Actions Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ "main" ]

permissions:
  contents: read
  packages: write
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the stack
        run: docker-compose up -d
      - name: Unit Test
      - run: docker-compose exec api python -m pytest "src/tests"
      - name: Smoke Test
        run: docker run --network container:file-browser-service appropriate/curl -s --retry 10 --retry-connrefused http://localhost:5000/api/
  
