name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  docker:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ytulu/file-browser-service:latest
            ytulu/file-browser-service:1.0.0
      -
        name: Build and push (ghcr.io)
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/ytulu/file-browser-service:latest
            ghcr.io/ytulu/file-browser-service:1.0.0
      -
        name: Run unit test
        uses: addnab/docker-run-action@v3
        with:
          image: ytulu/file-browser-service:latest
          run: python -m pytest "src/tests"
      - 
        name: Integration test
        run: docker run --network container:ytulu/file-browser-service:latest appropriate/curl -s --retry 10 --retry-connrefused http://localhost:5000/api/